package com.example.util

enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
    ENGLISH("en", "English", "🇬🇧"),
    SOMALI("so", "Soomaali", "🇸🇴"),
    ARABIC("ar", "العربية", "🇸🇦"),
    URDU("ur", "اردو", "🇵🇰")
}

object MultilingualStrings {
    fun getString(key: String, lang: AppLanguage): String {
        val map = when (lang) {
            AppLanguage.ENGLISH -> englishMap
            AppLanguage.SOMALI -> somaliMap
            AppLanguage.ARABIC -> arabicMap
            AppLanguage.URDU -> urduMap
        }
        return map[key] ?: englishMap[key] ?: key
    }

    private val englishMap = mapOf(
        "app_title" to "IshaQxaaDey Doom",
        "tagline" to "Play, Learn, Create, and Grow Together.",
        "nav_home" to "Home",
        "nav_games" to "Games",
        "nav_toddler" to "Toddler Zone",
        "nav_poems" to "Poems",
        "nav_studio" to "Studio",
        "nav_social" to "Community",
        "nav_parent" to "Parent Hub",
        "nav_profile" to "Profile",
        "daily_streak" to "Day Streak",
        "xp_points" to "XP",
        "stars" to "Stars",
        "gems" to "Gems",
        "learning_score" to "Learning Score",
        "trending_content" to "Trending for Kids",
        "featured_games" to "Featured Mini-Games",
        "popular_poems" to "Beloved Poems",
        "daily_challenges" to "Today's Missions",
        "play_now" to "Play Now",
        "read_poem" to "Read & Listen",
        "create_art" to "Open Studio",
        "share_artwork" to "Share Art",
        "save_artwork" to "Save Canvas",
        "safe_feed" to "Child-Safe Community Feed",
        "post_something" to "Share something kind...",
        "screen_time_limit" to "Parent Screen Time Control",
        "time_remaining" to "Time Remaining Today",
        "parent_pin_title" to "Parent Verification",
        "parent_pin_hint" to "Enter 4-digit Parent PIN",
        "login_title" to "Welcome to IshaQxaaDey!",
        "google_login" to "Continue with Google",
        "email_login" to "Login with Email",
        "signup" to "Create Free Account",
        "logout" to "Sign Out",
        "bubble_pop" to "Bubble Pop",
        "fruit_catcher" to "Fruit Catcher",
        "memory_match" to "Memory Match",
        "math_challenge" to "Math Challenge",
        "shape_matching" to "Shape Matching",
        "word_builder" to "Word Builder"
    )

    private val somaliMap = mapOf(
        "app_title" to "IshaQxaaDey Doom",
        "tagline" to "Ciyaar, Baro, Samee, oo Wada Kor.",
        "nav_home" to "Hoyga",
        "nav_games" to "Ciyaaraha",
        "nav_toddler" to "Aagga Carruurta",
        "nav_poems" to "Gabayada",
        "nav_studio" to "Istudiyaha",
        "nav_social" to "Bulshada",
        "nav_parent" to "Xarunta Waalidka",
        "nav_profile" to "Xogtaada",
        "daily_streak" to "Maalmo Isku Xiga",
        "xp_points" to "Dhibcaha XP",
        "stars" to "Xiddigaha",
        "gems" to "Dhagaxaanta",
        "learning_score" to "Dhibcaha Barashada",
        "trending_content" to "Waxyaabaha Ugu Caansan",
        "featured_games" to "Ciyaaro Carruureed",
        "popular_poems" to "Gabayo Caan ah",
        "daily_challenges" to "Hawlaha Maanta",
        "play_now" to "Ciyaar Hada",
        "read_poem" to "Akhri oo Dhageyso",
        "create_art" to "Fur Istudiyaha",
        "share_artwork" to "La Wadaag Sawirka",
        "save_artwork" to "Keydi Sawirka",
        "safe_feed" to "Qeybta Bulshada ee Nabdoon",
        "post_something" to "Qor wax wanaagsan...",
        "screen_time_limit" to "Xakameynta Waqtiga Shaashadda",
        "time_remaining" to "Waqtiga Hadhay Maanta",
        "parent_pin_title" to "Xaqiijinta Waalidka",
        "parent_pin_hint" to "Geli PIN-ka 4-ta lambar ah",
        "login_title" to "Ku soo dhowow IshaQxaaDey!",
        "google_login" to "Ku gal Google",
        "email_login" to "Ku gal Email",
        "signup" to "Sameyso Akoon Cusub",
        "logout" to "Ka bax",
        "bubble_pop" to "Balanbaalis Dilaac",
        "fruit_catcher" to "Miraha Qabo",
        "memory_match" to "Isku Eeg Xusuusta",
        "math_challenge" to "Tartan Xisaabeed",
        "shape_matching" to "Isku Beeg Qaababka",
        "word_builder" to "Dhisid Ereyo"
    )

    private val arabicMap = mapOf(
        "app_title" to "إشاقصادي دوم",
        "tagline" to "العب، تعلم، ابتكر، وانمُ معنا بأمان.",
        "nav_home" to "الرئيسية",
        "nav_games" to "الألعاب",
        "nav_toddler" to "واحة الصغار",
        "nav_poems" to "القصائد والأناشيد",
        "nav_studio" to "استوديو الإبداع",
        "nav_social" to "المجتمع الآمن",
        "nav_parent" to "لوحة الوالدين",
        "nav_profile" to "ملفي",
        "daily_streak" to "أيام متتالية",
        "xp_points" to "نقاط الخبرة",
        "stars" to "النجوم",
        "gems" to "الجواهر",
        "learning_score" to "نقاط التعلم",
        "trending_content" to "شائع للأطفال",
        "featured_games" to "ألعاب تعليمية مميزة",
        "popular_poems" to "أناشيد محبوبة",
        "daily_challenges" to "مهام اليوم",
        "play_now" to "العب الآن",
        "read_poem" to "اقرأ واستمع",
        "create_art" to "افتح الاستوديو",
        "share_artwork" to "شارك الرسمة",
        "save_artwork" to "حفظ اللوحة",
        "safe_feed" to "حائط أصدقائي الآمن",
        "post_something" to "شارك رسالة لطيفة...",
        "screen_time_limit" to "مراقبة وقت الشاشة",
        "time_remaining" to "الوقت المتبقي اليوم",
        "parent_pin_title" to "التحقق الأبوي",
        "parent_pin_hint" to "أدخل رمز PIN المكون من 4 أرقام",
        "login_title" to "مرحباً بكم في إشاقصادي دوم!",
        "google_login" to "المتابعة عبر Google",
        "email_login" to "تسجيل بالبريد الإلكتروني",
        "signup" to "إنشاء حساب جديد",
        "logout" to "تسجيل الخروج",
        "bubble_pop" to "فرقعة الفقاعات",
        "fruit_catcher" to "صائد الفواكه",
        "memory_match" to "تطابق الذاكرة",
        "math_challenge" to "تحدي الرياضيات",
        "shape_matching" to "مطابقة الأشكال",
        "word_builder" to "بناء الكلمات"
    )

    private val urduMap = mapOf(
        "app_title" to "اشاقصادی ڈوم",
        "tagline" to "کھیلو، سیکھو، تخلیق کرو اور ساتھ بڑھو۔",
        "nav_home" to "ہوم",
        "nav_games" to "کھیل",
        "nav_toddler" to "بچوں کا زون",
        "nav_poems" to "نظمیں",
        "nav_studio" to "اسٹوڈیو",
        "nav_social" to "محفوظ کمیونٹی",
        "nav_parent" to "والدین ڈیش بورڈ",
        "nav_profile" to "پروفائل",
        "daily_streak" to "مسلسل دن",
        "xp_points" to "ایکس پی",
        "stars" to "ستارے",
        "gems" to "ہیرے",
        "learning_score" to "سیکھنے کا اسکور",
        "trending_content" to "بچوں کی مقبول چیزیں",
        "featured_games" to "خصوصی منی گیمز",
        "popular_poems" to "پیاری نظمیں",
        "daily_challenges" to "آج کے مشن",
        "play_now" to "اب کھیلیں",
        "read_poem" to "پڑھیں اور سنیں",
        "create_art" to "آرٹ اسٹوڈیو کھولیں",
        "share_artwork" to "تصویر شیئر کریں",
        "save_artwork" to "تصویر محفوظ کریں",
        "safe_feed" to "بچوں کی محفوظ کمیونٹی",
        "post_something" to "کوئی اچھی بات لکھیں...",
        "screen_time_limit" to "اسکرین ٹائم کنٹرول",
        "time_remaining" to "آج کا بچا ہوا وقت",
        "parent_pin_title" to "والدین کی تصدیق",
        "parent_pin_hint" to "4 ہندسوں کا پن درج کریں",
        "login_title" to "اشاقصادی میں خوش آمدید!",
        "google_login" to "گوگل کے ساتھ لاگ ان کریں",
        "email_login" to "ای میل کے ساتھ لاگ ان کریں",
        "signup" to "نیا اکاؤنٹ بنائیں",
        "logout" to "لاگ آؤٹ",
        "bubble_pop" to "بلبلے پھوڑیں",
        "fruit_catcher" to "پھل پکڑیں",
        "memory_match" to "یادداشت کا کھیل",
        "math_challenge" to "ریاضی کا چیلنج",
        "shape_matching" to "اشکال کی پہچان",
        "word_builder" to "الفاظ سازی"
    )
}
